import { Plane, FileText, Hotel, Shield, Car, Compass, HeartHandshake, Building2, Star } from "lucide-react"

export interface Package {
  id: string
  name: string
  duration: string
  price: number
  currency: string
  description: string
  highlights: string[]
  image: string
}

export interface Service {
  id: string
  slug: string
  icon: any
  title: string
  shortTitle: string
  description: string
  longDescription: string
  features: string[]
  color: string
  packages: Package[]
}

export const servicesData: Service[] = [
  {
    id: "air-ticketing",
    slug: "air-ticketing",
    icon: Plane,
    title: "Air Ticketing",
    shortTitle: "Air Ticketing",
    description:
      "International & Domestic flight booking with GDS/OTA API integration, refund, reissue & date change support.",
    longDescription:
      "We provide comprehensive air ticketing services with access to all major airlines through GDS and OTA API integrations. Our team ensures competitive pricing, flexible booking options, and complete post-booking support including refunds, reissues, and date changes.",
    features: [
      "International & Domestic Flight Booking",
      "GDS / OTA API Integration",
      "Refund Support",
      "Reissue & Date Change Support",
      "Best price guarantee",
      "24/7 Customer Support",
    ],
    color: "from-sky-500 to-sky-600",
    packages: [
      {
        id: "dhaka-bangkok",
        name: "Dhaka to Bangkok",
        duration: "Round Trip",
        price: 32900,
        currency: "BDT",
        description: "Direct flights to Bangkok with flexible dates and baggage included.",
        highlights: ["Direct flight", "23kg baggage", "Meal included", "Free date change"],
        image: "/bangkok-city-skyline-with-modern-skyscrapers.jpg",
      },
      {
        id: "dhaka-dubai",
        name: "Dhaka to Dubai",
        duration: "Round Trip",
        price: 45900,
        currency: "BDT",
        description: "Premium flights to Dubai with excellent connectivity and services.",
        highlights: ["Multiple airlines", "30kg baggage", "In-flight entertainment", "Transit lounge access"],
        image: "/dubai-burj-khalifa-skyline-sunset-view.jpg",
      },
      {
        id: "dhaka-london",
        name: "Dhaka to London",
        duration: "Round Trip",
        price: 89900,
        currency: "BDT",
        description: "Premium long-haul flights to London with top airlines.",
        highlights: ["Via Dubai/Doha", "40kg baggage", "Premium economy available", "Lounge access"],
        image: "/london-big-ben-and-tower-bridge-landmarks.jpg",
      },
    ],
  },
  {
    id: "tour-packages",
    slug: "tour-packages",
    icon: Compass,
    title: "Tour Packages",
    shortTitle: "Tour Packages",
    description:
      "International group tours, customized holiday packages, honeymoon packages, corporate tours & family vacation packages.",
    longDescription:
      "Explore the world with our carefully curated tour packages. We offer international group tours, customized holiday experiences, romantic honeymoon packages, corporate team-building tours, and memorable family vacations with complete arrangements.",
    features: [
      "International Group Tours",
      "Customized Holiday Packages",
      "Honeymoon Packages",
      "Corporate Tours",
      "Family Vacation Packages",
      "Expert Local Guides",
    ],
    color: "from-teal-500 to-teal-600",
    packages: [
      {
        id: "maldives-honeymoon",
        name: "Maldives Honeymoon Package",
        duration: "5 Days / 4 Nights",
        price: 125000,
        currency: "BDT",
        description: "Romantic overwater villa experience with private beach dinners and spa.",
        highlights: [
          "Overwater villa",
          "Private beach dinner",
          "Couples spa",
          "Snorkeling tour",
          "All meals included",
          "Airport transfers",
        ],
        image: "/maldives-overwater-bungalow-crystal-clear-water.jpg",
      },
      {
        id: "thailand-group",
        name: "Thailand Group Tour",
        duration: "6 Days / 5 Nights",
        price: 48900,
        currency: "BDT",
        description: "Explore Bangkok and Pattaya with group activities and cultural experiences.",
        highlights: [
          "4-star hotels",
          "Safari World",
          "Coral Island",
          "Temple tours",
          "Group activities",
          "All transfers",
        ],
        image: "/thailand-grand-palace-bangkok-golden-temple.jpg",
      },
      {
        id: "europe-family",
        name: "Europe Family Vacation",
        duration: "10 Days / 9 Nights",
        price: 285000,
        currency: "BDT",
        description: "Multi-country European tour covering France, Switzerland, and Italy.",
        highlights: [
          "3 countries tour",
          "Family-friendly hotels",
          "Eiffel Tower visit",
          "Swiss Alps",
          "Venice gondola",
          "Schengen visa support",
        ],
        image: "/paris-eiffel-tower-with-european-cityscape.jpg",
      },
    ],
  },
  {
    id: "hotel-booking",
    slug: "hotel-booking",
    icon: Hotel,
    title: "Hotel Booking",
    shortTitle: "Hotel Booking",
    description: "Budget, luxury & resort accommodation with direct contracted hotels and global API connectivity.",
    longDescription:
      "Access to a wide range of accommodation options from budget-friendly hotels to luxury resorts. We maintain direct contracts with premium properties and leverage global API connectivity to ensure competitive rates and instant confirmations.",
    features: [
      "Budget Hotels",
      "Luxury Accommodations",
      "Resort Properties",
      "Direct Contracted Hotels",
      "Global API Connectivity",
      "Instant Confirmation",
    ],
    color: "from-purple-500 to-purple-600",
    packages: [
      {
        id: "dubai-luxury",
        name: "Dubai Luxury Hotel",
        duration: "Per Night",
        price: 15000,
        currency: "BDT",
        description: "5-star luxury hotel in downtown Dubai with Burj Khalifa view.",
        highlights: [
          "5-star property",
          "Burj view rooms",
          "Pool & spa access",
          "Breakfast buffet",
          "Free WiFi",
          "Airport shuttle",
        ],
        image: "/luxury-hotel-room-with-dubai-skyline-view.jpg",
      },
      {
        id: "maldives-resort",
        name: "Maldives Beach Resort",
        duration: "Per Night",
        price: 25000,
        currency: "BDT",
        description: "Beachfront resort with overwater villas and all-inclusive options.",
        highlights: [
          "Overwater villa",
          "Private beach",
          "All meals included",
          "Water sports",
          "Spa services",
          "Diving center",
        ],
        image: "/maldives-luxury-resort-with-beach-and-palm-trees.jpg",
      },
      {
        id: "bangkok-budget",
        name: "Bangkok Budget Hotel",
        duration: "Per Night",
        price: 3500,
        currency: "BDT",
        description: "Comfortable 3-star hotel in central Bangkok near shopping areas.",
        highlights: [
          "Central location",
          "BTS access",
          "Breakfast included",
          "Free WiFi",
          "24/7 reception",
          "Clean & comfortable",
        ],
        image: "/modern-budget-hotel-room-in-bangkok.jpg",
      },
    ],
  },
  {
    id: "visa-assistance",
    slug: "visa-assistance",
    icon: FileText,
    title: "Visa Assistance",
    shortTitle: "Visa Assistance",
    description:
      "Tourist, business & e-visa support with complete document preparation and embassy/VAC appointment assistance.",
    longDescription:
      "Expert visa assistance for all your travel needs. We provide comprehensive support for tourist visas, business visas, and e-visa applications. Our services include complete document preparation, application review, and embassy or VAC appointment scheduling to ensure high approval rates.",
    features: [
      "Tourist Visa",
      "Business Visa",
      "E-Visa Support",
      "Complete Document Preparation",
      "Embassy/ VAC Appointment Assistance",
      "High Approval Rate",
    ],
    color: "from-blue-500 to-blue-600",
    packages: [
      {
        id: "schengen-visa",
        name: "Schengen Tourist Visa",
        duration: "Processing: 15-20 Days",
        price: 8500,
        currency: "BDT",
        description: "Complete Schengen visa assistance for 26 European countries.",
        highlights: [
          "26 countries access",
          "Full documentation",
          "Appointment booking",
          "Interview coaching",
          "Application review",
          "Courier service",
        ],
        image: "/european-passport-with-schengen-visa-stamp.jpg",
      },
      {
        id: "dubai-evisa",
        name: "UAE E-Visa",
        duration: "Processing: 3-4 Days",
        price: 12500,
        currency: "BDT",
        description: "Fast UAE e-visa processing with insurance included.",
        highlights: [
          "30 days stay",
          "Express processing",
          "OK to board",
          "Insurance included",
          "Online delivery",
          "Multiple entry option",
        ],
        image: "/uae-visa-document-with-dubai-landmarks.jpg",
      },
      {
        id: "uk-business-visa",
        name: "UK Business Visa",
        duration: "Processing: 15-21 Days",
        price: 15000,
        currency: "BDT",
        description: "UK business visa with invitation letter support and documentation.",
        highlights: [
          "6 months validity",
          "Invitation letter support",
          "Document preparation",
          "VFS appointment",
          "Interview prep",
          "Priority service available",
        ],
        image: "/uk-business-visa-with-london-skyline.jpg",
      },
    ],
  },
  {
    id: "airport-transfer",
    slug: "airport-transfer",
    icon: Car,
    title: "Airport Transfer",
    shortTitle: "Airport Transfer",
    description: "Private car transfer, shuttle services, premium limousine, and airport–hotel pickup & drop services.",
    longDescription:
      "Reliable and comfortable airport transfer services for stress-free travel. Choose from private car transfers, shared shuttle services, or premium limousine options. We provide seamless airport-to-hotel and hotel-to-airport transportation with professional drivers.",
    features: [
      "Private Car Transfer",
      "Shuttle Services",
      "Premium Limousine",
      "Airport–Hotel Pickup & Drop",
      "Professional Drivers",
      "Flight Tracking",
    ],
    color: "from-orange-500 to-orange-600",
    packages: [
      {
        id: "dhaka-airport-private",
        name: "Dhaka Airport Private Transfer",
        duration: "One Way",
        price: 2500,
        currency: "BDT",
        description: "Private car transfer from Dhaka airport to city hotels.",
        highlights: [
          "Private sedan",
          "Meet & greet",
          "Flight tracking",
          "Free waiting time",
          "Luggage assistance",
          "AC vehicle",
        ],
        image: "/luxury-sedan-car-at-airport-terminal.jpg",
      },
      {
        id: "dubai-limousine",
        name: "Dubai Premium Limousine",
        duration: "One Way",
        price: 8500,
        currency: "BDT",
        description: "Luxury limousine service in Dubai with VIP treatment.",
        highlights: [
          "Mercedes/BMW",
          "Chauffeur service",
          "VIP lounge access",
          "Complimentary water",
          "Child seat available",
          "Premium experience",
        ],
        image: "/black-luxury-limousine-at-dubai-airport.jpg",
      },
      {
        id: "shared-shuttle",
        name: "Shared Airport Shuttle",
        duration: "One Way",
        price: 800,
        currency: "BDT",
        description: "Affordable shared shuttle service to major city hotels.",
        highlights: [
          "Budget-friendly",
          "AC minibus",
          "Multiple stops",
          "Fixed schedule",
          "Luggage space",
          "Safe & reliable",
        ],
        image: "/airport-shuttle-bus-with-passengers.jpg",
      },
    ],
  },
  {
    id: "holiday-planning",
    slug: "holiday-planning",
    icon: HeartHandshake,
    title: "Holiday Planning & Travel Consultation",
    shortTitle: "Holiday Planning",
    description:
      "Tailor-made itineraries, budget & travel cost planning, and country-wise travel rules & requirements.",
    longDescription:
      "Expert holiday planning and travel consultation services to make your dream vacation a reality. We create customized itineraries based on your preferences, provide detailed budget planning, and keep you informed about country-specific travel requirements and regulations.",
    features: [
      "Tailor-Made Itineraries",
      "Budget & Travel Cost Planning",
      "Country-Wise Travel Rules & Requirements",
      "Destination Recommendations",
      "Activity Planning",
      "Expert Consultation",
    ],
    color: "from-pink-500 to-pink-600",
    packages: [
      {
        id: "custom-europe-plan",
        name: "Custom Europe Itinerary",
        duration: "Consultation Package",
        price: 5000,
        currency: "BDT",
        description: "Personalized European travel itinerary with budget planning.",
        highlights: [
          "Multi-country planning",
          "Accommodation recommendations",
          "Transport booking",
          "Budget optimization",
          "Travel tips",
          "24/7 support",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "honeymoon-planning",
        name: "Honeymoon Planning Service",
        duration: "Complete Package",
        price: 8000,
        currency: "BDT",
        description: "Romantic honeymoon planning with special touches and experiences.",
        highlights: [
          "Romantic destinations",
          "Special experiences",
          "Luxury accommodations",
          "Private tours",
          "Surprise arrangements",
          "Complete coordination",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "family-vacation-plan",
        name: "Family Vacation Planning",
        duration: "Consultation Package",
        price: 6000,
        currency: "BDT",
        description: "Family-friendly travel planning with kid-friendly activities and hotels.",
        highlights: [
          "Family destinations",
          "Kid-friendly hotels",
          "Activity planning",
          "Safety considerations",
          "Budget management",
          "Flexible itineraries",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
  {
    id: "travel-insurance",
    slug: "travel-insurance",
    icon: Shield,
    title: "Travel Insurance",
    shortTitle: "Travel Insurance",
    description: "Medical, baggage & trip cancellation insurance with Europe/Schengen/worldwide coverage.",
    longDescription:
      "Comprehensive travel insurance coverage to protect your journey. Our insurance plans cover medical emergencies, baggage loss or damage, trip cancellations, and more. We offer specialized coverage for Europe, Schengen countries, and worldwide destinations.",
    features: [
      "Medical Insurance",
      "Baggage Insurance",
      "Trip Cancellation Insurance",
      "Europe / Schengen Coverage",
      "Worldwide Coverage",
      "Emergency Assistance",
    ],
    color: "from-green-500 to-green-600",
    packages: [
      {
        id: "schengen-insurance",
        name: "Schengen Travel Insurance",
        duration: "30 Days Coverage",
        price: 3500,
        currency: "BDT",
        description: "Mandatory Schengen visa insurance with €50,000 coverage.",
        highlights: [
          "€50,000 medical cover",
          "26 countries valid",
          "Visa compliant",
          "Emergency evacuation",
          "24/7 assistance",
          "Instant policy",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "worldwide-insurance",
        name: "Worldwide Travel Insurance",
        duration: "Annual Coverage",
        price: 15000,
        currency: "BDT",
        description: "Comprehensive annual travel insurance for frequent travelers.",
        highlights: [
          "Global coverage",
          "Unlimited trips",
          "Medical $100,000",
          "Baggage protection",
          "Trip cancellation",
          "Personal liability",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "asia-insurance",
        name: "Asia Travel Insurance",
        duration: "15 Days Coverage",
        price: 2000,
        currency: "BDT",
        description: "Affordable insurance for Asian countries travel.",
        highlights: [
          "$30,000 medical cover",
          "Asian countries",
          "Baggage protection",
          "Personal accident",
          "Emergency assistance",
          "Budget-friendly",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
  {
    id: "corporate-travel",
    slug: "corporate-travel",
    icon: Building2,
    title: "Group & Corporate Travel Services",
    shortTitle: "Corporate Travel",
    description:
      "Corporate travel management, MICE (Meeting, Incentive, Conference & Exhibition), and annual employee trips.",
    longDescription:
      "Specialized corporate travel management services for businesses. We handle all aspects of corporate travel including flight bookings, hotel accommodations, MICE events, team-building activities, and annual employee trips with complete coordination and budget management.",
    features: [
      "Corporate Travel Management",
      "MICE Services",
      "Meeting & Conference Planning",
      "Incentive Trips",
      "Annual Employee Trips",
      "Group Coordination",
    ],
    color: "from-indigo-500 to-indigo-600",
    packages: [
      {
        id: "corporate-bangkok",
        name: "Bangkok Corporate Trip",
        duration: "4 Days / 3 Nights",
        price: 55000,
        currency: "BDT",
        description: "Corporate group trip to Bangkok with team-building activities.",
        highlights: [
          "4-star hotel",
          "Team activities",
          "Meeting facilities",
          "Group transfers",
          "Welcome dinner",
          "Professional coordination",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "mice-singapore",
        name: "Singapore MICE Package",
        duration: "3 Days / 2 Nights",
        price: 75000,
        currency: "BDT",
        description: "Complete MICE services in Singapore with conference facilities.",
        highlights: [
          "Convention center",
          "5-star hotel",
          "A/V equipment",
          "Catering services",
          "City tour",
          "Gala dinner",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "annual-trip-dubai",
        name: "Dubai Annual Employee Trip",
        duration: "5 Days / 4 Nights",
        price: 68000,
        currency: "BDT",
        description: "Exciting annual employee trip to Dubai with leisure activities.",
        highlights: [
          "4-star hotel",
          "Desert safari",
          "Burj Khalifa visit",
          "Dubai Mall tour",
          "Dhow cruise",
          "All meals included",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
  {
    id: "umrah-religious-tours",
    slug: "umrah-religious-tours",
    icon: Star,
    title: "Umrah & Religious Tour Services",
    shortTitle: "Umrah Services",
    description:
      "Complete Umrah packages, Umrah visa processing, 5-star/4-star hotel accommodation, and Ziyarat tours.",
    longDescription:
      "Sacred journey packages with complete arrangements for a blessed pilgrimage experience. We provide comprehensive Umrah services including visa processing, premium accommodations near Haram, guided Ziyarat tours, and 24/7 spiritual support throughout your journey.",
    features: [
      "Complete Umrah Packages",
      "Umrah Visa Processing",
      "5-Star / 4-Star Hotel Accommodation",
      "Ziyarat Tours",
      "Guided Religious Tours",
      "24/7 Support",
    ],
    color: "from-emerald-500 to-emerald-600",
    packages: [
      {
        id: "umrah-economy",
        name: "Economy Umrah Package",
        duration: "10 Days / 9 Nights",
        price: 145000,
        currency: "BDT",
        description: "Affordable Umrah package with comfortable 3-star accommodations.",
        highlights: [
          "3-star hotels",
          "500m from Haram",
          "Return flights",
          "Visa included",
          "Ziyarat tours",
          "Group departure",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "umrah-premium",
        name: "Premium Umrah Package",
        duration: "14 Days / 13 Nights",
        price: 225000,
        currency: "BDT",
        description: "Premium experience with 5-star hotels and exclusive services.",
        highlights: [
          "5-star hotels",
          "Haram view rooms",
          "Emirates/Qatar Airways",
          "VIP transfers",
          "Personal guide",
          "All inclusive",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
      {
        id: "umrah-family",
        name: "Family Umrah Package",
        duration: "12 Days / 11 Nights",
        price: 195000,
        currency: "BDT",
        description: "Family-friendly package with spacious rooms and kid-friendly services.",
        highlights: [
          "Family rooms",
          "4-star hotels",
          "Kid-friendly meals",
          "Flexible schedule",
          "Extra luggage",
          "Family coordination",
        ],
        image: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return servicesData.find((service) => service.slug === slug)
}

export function getPackageById(serviceSlug: string, packageId: string): Package | undefined {
  const service = getServiceBySlug(serviceSlug)
  return service?.packages.find((pkg) => pkg.id === packageId)
}
